var markers = [
{
    "id":1,
    "type_point":"Pizza",
    "location_latitude":48.865633,
    "location_longitude":2.321236,
    "map_image_url":"img/thumb_map_single_restaurant.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Da Alfredo",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"detail-restaurant.html"
  },
  {
    "id":2,
    "type_point":"Burghers",
    "location_latitude":48.854183,
    "location_longitude":2.354808,
    "map_image_url":"img/thumb_map_single_restaurant.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Best Burghers",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"detail-restaurant.html"
  },
  {
    "id":3,
    "type_point":"Vegetarian",
    "location_latitude":48.863893,
    "location_longitude":2.342348,
    "map_image_url":"img/thumb_map_single_restaurant.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Vego Life",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"detail-restaurant.html"
  },
  {
    "id":4,
    "type_point":"Japanese",
    "location_latitude":48.858370,
    "location_longitude":2.294481,
    "map_image_url":"img/thumb_map_single_restaurant.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Sushi Temple",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"detail-restaurant.html"
  },
  {
    "id":5,
    "type_point":"Pizza",
    "location_latitude":48.837273,
    "location_longitude":2.335387,
    "map_image_url":"img/thumb_map_single_restaurant.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Auto Pizza",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"detail-restaurant.html"
  },
  {
    "id":6,
    "type_point":"Burghers",
    "location_latitude":48.860819,
    "location_longitude":2.354507,
    "map_image_url":"img/thumb_map_single_restaurant.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Alliance",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"detail-restaurant.html"
  },
  {
    "id":7,
    "type_point":"Chinese",
    "location_latitude":48.853798,
    "location_longitude":2.333328,
    "map_image_url":"img/thumb_map_single_restaurant.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Alliance",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"detail-restaurant.html"
  },
  {
    "id":8,
    "type_point":"Sushi",
    "location_latitude":48.862880,
    "location_longitude":2.287205,
    "map_image_url":"img/thumb_map_single_restaurant.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Dragon Tower",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"detail-restaurant.html"
  },
  {
    "id":9,
    "type_point":"Mexican",
    "location_latitude":48.865784,
    "location_longitude":2.307314,
    "map_image_url":"img/thumb_map_single_restaurant.jpg",
    "rate":"Superb | 7.5",
    "name_point":"El Paso",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"detail-restaurant.html"
  },
  {
    "id":10,
    "type_point":"Bakery",
    "location_latitude":48.852729,
    "location_longitude":2.350564,
    "map_image_url":"img/thumb_map_single_restaurant.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Monnalisa",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"detail-restaurant.html"
  }
];
